<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Manage users' => 'Gestionar usuarios',
    'My songs' => 'Mis canciones',
    'Delete' => 'Eliminar',
    'Songs' => 'Canciones',
    'Create' => 'Agregar',
    'Create song' => 'Agregar cancion',
    'Letter' => 'Letra',
    'Upload date' => 'Fecha de subida',
    'Year of creation' => 'Año de creación',
    'Author' => 'Autor',
    'Gender' => 'Genero',
    'Title' => 'Titulo',
    'Song' => 'Cancion',
    'Total Views' => 'Total reproducciones',
    'This Nick name has already been taken' => 'Este apodo ya ha sido utilizado.',
    'Nick name or email' => 'Apodo o correo electrónico',
    'Settings' => 'Configuración',
    'Password repeat' => 'Repita Contraseña',
    'Contact' => 'Contacto',
    'About' => 'Acerca de',
    'Search' => 'Buscar',
    'Logout' => 'Salir',
    'Please fill out the following fields to login:' => 'Por favor llene los siguientes campos:',
    'Login' => 'Entrar',
    'Signup' => 'Regístrate',
    'Signin' => 'Registrarse',
    'Contact' => 'Contactenos',
    'About' => 'Acerca de',
    'Home' => 'Inicio',
    'Incorrect username or password.' => 'Usuario o contraseña incorrecta.',
    'Profile' => 'Perfil',
    'I forgot my password' => 'Olvidé mi contraseña',
    'About' => 'Acerca de',
    'By song' => 'Por canción',
    'Contact' => 'Contactenos',
    'Create user' => 'Crear usuario',
    'Create' => 'Crear',
    'Email' => 'Correo electrónico',
    'Home' => 'Inicio',
    'Incorrect username or password.' => 'Usuario o contraseña incorrecta.',
    'Logout' => 'Salir',
    'Login' => 'Entrar',
    'Photo' => 'Foto',
    'Last names' => 'Apellidos',
    'First names' => 'Nombres',
    'Nick name' => 'Apodo',
    'Please fill out the following fields to login:' => 'Por favor llene los siguientes campos:',
    'Password' => 'Contraseña',
    'RememberMe' => 'Recuerdame',
    'Sign Up' => 'Regístrate',
    'Sign In' => 'Registrarse',
    'Search by song or artist' => 'Buscar por canción o artista',
    'Songs' => 'Canciones',
    'Type' => 'Tipo',
    'Users' => 'Usuarios',
    'Update song' => 'Actualizar cancion',
    'Update user' => 'Actualizar usuario',
    'Update' => 'Actualizar',
];
